django-img/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

django-img/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

django-img/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django-img/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

django-img/community/models.py
from django.db import models
from django.conf import settings


class Review(models.Model):
    img = models.ImageField(upload_to='uploads/%Y/%m/%d/', blank=True)


class Comment(models.Model):
    content = models.CharField(max_length=100)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

django-img/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

django-img/community/forms.py
from django import forms
from community.models import Review, Comment


class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = '__all__'


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['review', 'user']

django-img/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from .forms import CustomUserCreationForm
from django.http import JsonResponse


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('community:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'community:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    auth_logout(request)
    return redirect('community:index')


@login_required
def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), pk=user_pk)
        user = request.user
        if person != user:
            if person.followers.filter(pk=user.pk).exists():
                person.followers.remove(user)
                is_followed = False
            else:
                person.followers.add(user)
                is_followed = True
            context = {
                'is_followed': is_followed,
                'follower_count': person.followers.count(),
                'following_count': person.followings.count()
            }
            return JsonResponse(context)
        return redirect('accounts:profile', person.username)
    return redirect('accounts:login')

django-img/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from community.models import Review
from community.forms import ReviewForm, CommentForm
from django.http import JsonResponse

@require_GET
def index(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews': reviews,

    }
    return render(request, 'community/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES) 
        if form.is_valid():
            review = form.save(commit=False)
            review.save()
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form': form,
    }
    return render(request, 'community/create.html', context)


@require_GET
def detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comments = review.comment_set.all()
    comment_form = CommentForm()
    context = {
        'review': review,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'community/detail.html', context)


@require_POST
def create_comment(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        return redirect('community:detail', review.pk)
    context = {
        'comment_form': comment_form,
        'review': review,
        'comments': review.comment_set.all(),
    }
    return render(request, 'community/detail.html', context)


@require_POST
def like(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        user = request.user

        if review.like_users.filter(pk=user.pk).exists():
            review.like_users.remove(user)
            is_liked = False
        else:
            review.like_users.add(user)
            is_liked = True
        
        context = {
            'is_liked': is_liked,
            'like_count': review.like_users.count()

        }

        return JsonResponse(context)
        # return redirect('community:index')
    return redirect('accounts:login')

django-img/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<h1>로그인</h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form%}
  <input type="submit">
</form>
{% endblock  %}

django-img/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ person.username }}의 프로필 페이지</h1>
  {% with followings=person.followings.all followers=person.followers.all %}
    <div>
      <div id="follow-div">
        팔로잉 : {{ followings|length }} / 팔로워 : {{ followers|length }}
      </div>
      {% if user != person %}
        <div>
          <form id="follow-form" data-user-id="{{ person.pk }}">
            {% csrf_token %}
            {% if user in followers %}
              <button id="followBtn" type="submit">언팔로우</button>
            {% else %}
              <button id="followBtn" type="submit">팔로우</button>
            {% endif %}
          </form>
        </div>
      {% endif %}
    </div>
  {% endwith %}
{% endblock content %}


{% block script %}
  <script>
    const form = document.querySelector('#follow-form')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    form.addEventListener('submit', function (event) {
      event.preventDefault()
      const userId = event.target.dataset.userId
      axios({
        method:'POST',
        url:`/accounts/${userId}/follow/`,
        headers: {'X-CSRFToken': csrftoken,}
      })
      .then((response) => {
          const followBtn = document.querySelector('#followBtn')
          const followDiv = document.querySelector('#follow-div')
          const is_followed = response.data.is_followed
          console.log(is_followed)
          followBtn.innerText = is_followed ? '언팔로우': '팔로우'
          followDiv.innerText = 
          `팔로잉 : ${response.data.following_count} / 팔로워 : ${response.data.follower_count}`
        })
    })
  </script>
{% endblock script %}

django-img/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<h1>회원가입</h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form%}
  <input type="submit">
</form>
{% endblock  %}

django-img/community/templates/community/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1 class="text-center">CREATE</h1>
  <form action="{% url 'community:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'community:index' %}">[back]</a>
{% endblock %}

django-img/community/templates/community/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h2 class="text-center">DETAIL</h2>
  <h3>{{ review.pk }} 번째 글</h3>
  <hr>
  <img src="{% url 'community.img.url' %}" alt="">
  <hr>
  <h4>댓글 목록</h4>
  {% if comments|length %}
    <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
  {% endif %}
  {% for comment in comments %}
    <div>
      {{ comment.user }} - {{ comment.content }}
    </div>
  {% empty %}
    <p><b>댓글이 없어요..</b></p>
  {% endfor %}
  <hr>
  {% if user.is_authenticated %}
    <form action="{% url 'community:create_comment' review.pk %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form comment_form %}
      <input type="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
  {% endif %}
  <a href="{% url 'community:index' %}">[back]</a>
{% endblock  %}

django-img/community/templates/community/index.html
{% extends 'base.html' %}


{% block content %}
  <h1>Community</h1>
  <hr>
  {% for review in reviews %}
    <p>작성자 : <a href="{% url 'accounts:profile' review.user.username %}">{{ review.user }}</a></p>
    <p>글 번호: {{ review.pk }}</p>
    <p>글 제목: {{ review.title }}</p>
    <p>글 내용: {{ review.content }}</p>
    <form id="likeForm" data-review-id="{{ review.pk }}">
      {% csrf_token %}
      {% if user in review.like_users.all %}
        <button id="btn{{ review.pk }}"><i class="fa-sharp fa-solid fa-heart" style="color: red; font-size: 3em;"></i></button>
      {% else %}
        <button id="btn{{ review.pk }}"><i class="fa-sharp fa-solid fa-heart" style="color: gray; font-size: 3em;"></i></button>
      {% endif %}
    </form>
    <p id="likeP{{ review.pk }}">
      <span>{{ review.like_users.all|length }}</span> 명이 이 글을 좋아합니다.
    </p>
    <a href="{% url 'community:detail' review.pk %}">[detail]</a>
    <hr>
  {% endfor %}
{% endblock %}

{% block script %}
<script>
  const likeForms = document.querySelectorAll('#likeForm')
  

  const likeFunc = (event) => {
    event.preventDefault()
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    const username = event.target.dataset.reviewId
    // console.log(username)
    axios({
      method: 'POST',
      url: `/community/${username}/like/`,
      headers: {'X-CSRFToken': csrftoken,}
    })
    .then((res) => {
      const isLiked = res.data.is_liked
      const likeBtn = document.querySelector('#btn'+username)
      console.log(likeBtn.innerHTML)
      likeBtn.innerHTML = isLiked ? '<i class="fa-sharp fa-solid fa-heart" style="color: red; font-size: 3em;"></i>' : '<i class="fa-sharp fa-solid fa-heart" style="color: gray; font-size: 3em;"></i>'
      // likeBtn.innerText = isLiked ? '안좋아요' : '좋아요'
      const likeP = document.querySelector('#likeP'+username)
      const likeCount = res.data.like_count
      likeP.innerText = `${likeCount} 명이 이 글을 좋아합니다.`
      // console.log(likeP)
    })
  }

  likeForms.forEach((form) => {
    form.addEventListener('submit', likeFunc)
  })
</script>


{% endblock script %}

django-img/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <style>
    #card-div:hover {
      transform: scale(1.05);
      box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
    }
    * {
      font-family: 'Noto Sans KR', sans-serif;
    }
    button {
      border: 1px white solid;
      background-color: white;
    }
    a {
      text-decoration: none
    }
    a:hover {
      transform: scale(1.05);
      box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
    }<style>
      .card:hover{
        transform: scale(1.05);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
      }
      .modal {
        position: fixed;
        background-color: rgba(0, 0, 0, 0.5);
        top: 0;
        height: 100vh;
        width: 100vw;
        display: none;
        justify-content: center;
        align-items: center;
      }
      .modal-content {
        width: 100%;
        height: 20rem;
        background-color: #60A5FA;
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 2rem;
        color: white;
        animation: move 2s ease-in-out;
      }
      .modal{
        break-word:normal;
      }
  </style>
  <title>Document</title>
</head>
<body>
  <div class="container">
    <nav class="d-flex justify-content-between navbar-dark navbar bg-dark navbar-expand-md sticky-top">
      {% if user.is_authenticated %}
      <div class="d-flex mx-3">
        <img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fk.kakaocdn.net%2Fdn%2FXgwGp%2FbtrQq445WD3%2Fr2Nt0k2hRnBR3uclMiaMTK%2Fimg.png" style="height:30px;">
        <a href="{% url 'community:index'%}" class="mx-3 text-white" >Community</a>
        <a href="{% url 'community:create'%}" class="mx-3 text-white" >New Review</a>
      </div>
      
      <div class="d-flex">
        <a href="{% url 'accounts:profile' user %}" class="text-white mx-3"><h3>Hello, {{ user.username }}</h3></a>
        <form action="{% url 'accounts:logout' %}" method="POST" class="mx-3">
          {% csrf_token %}
          <input type="submit" value="Logout" class="btn btn-light">
        </form>
      </div>

      {% else %}
      <div>
        <a href="{% url 'accounts:signup' %}" class="mx-3 text-white">Signup</a>
        <a href="{% url 'accounts:login' %}" class="mx-3 text-white">Login</a>
      </div>
      {% endif %}
    </nav>
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="https://kit.fontawesome.com/703c5975bf.js" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock script %}
</body>
</html>